site_name: CodeLab Adapter
repo_url: https://github.com/CodeLabClub/codelab-adapter-docs
edit_uri: edit/v2/docs/
site_description: the docs
extra_javascript:
    - 'js/baidu-tongji.js'
theme:
  name: material
  language: "zh"
  palette:
    primary: "Light Blue"
    accent: "Light Blue"
  feature:
    tabs: false
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  # - pyembed.markdown

# extra:
#   disqus: 'https-adapter-codelab-club'

# Navigation
nav:
  - 主页(Home): "index.md"
  # - 用户手册(user guide):
  - Getstart: 
      - Adapter简介: "get_start/gs_adapter_intro.md"
      - 安装Adapter: "get_start/gs_install.md"
      - 入门案例1: "get_start/gs_pyproject.md"
      - 入门案例2: "get_start/gs_microbit.md"
  - 用户手册(user guide):
      # - 安装(install): "user_guide/install.md"
      # - 下载(download): 'user_guide/develop.md'
      # - 使用(usage): "user_guide/usage.md"
      - 进阶(advanced): "user_guide/advanced.md"
      - 展示视频(gallery): "user_guide/gallery.md"
      - 常见问题(FAQ): "user_guide/FAQ.md"
      - 配置文件(settings): "user_guide/settings.md"
      - 将 Scratch 项目嵌入网站: "user_guide/嵌入scratch.md"
      - 与外部系统通信: "user_guide/与外部系统通信.md"
      - 历史(changelog): "changelog.md"
  - Scratch Projects:
      - 介绍(introduction): "Scratch_Projects/introduction.md"
      - 音乐主题活动: "Scratch_Projects/音乐主题活动.md"
      - Scratch PPT: "Scratch_Projects/scratch_ppt.md"
      - 霍格沃兹: "Scratch_Projects/霍格沃兹.md"
      - cube symphony: "Scratch_Projects/cube_symphony.md"
      - 彩虹的旋律: "Scratch_Projects/彩虹的旋律.md"
      - 击掌奏乐: "Scratch_Projects/击掌奏乐.md"
      - 目之所及: "Scratch_Projects/目之所及.md"
      - 芝麻开门: "Scratch_Projects/芝麻开门.md"
      - 纸做的开关: "Scratch_Projects/纸做的开关.md"
      - 自制门禁系统: "Scratch_Projects/自制门禁系统.md"
      - 灰袍巫师: "Scratch_Projects/灰袍巫师.md"
      - 鼻梁上的老花镜: "Scratch_Projects/鼻梁上的老花镜.md"
      - 闭眼请熄灯: "Scratch_Projects/闭眼请熄灯.md"
      - 击灭那盏灯: "Scratch_Projects/击灭那盏灯.md"
      - 手势窗帘: "Scratch_Projects/手势窗帘.md"
      - 正在读书: "Scratch_Projects/i_am_reading.md"
      - 搜索: "Scratch_Projects/搜索.md"
      - 聊天机器人: "Scratch_Projects/聊天机器人.md"
  - Python Projects:
      - 介绍(introduction): "Python_Projects/introduction.md"
      - 安装Python.md: "Python_Projects/install_python.md"
      - I am reading!: "Python_Projects/I_am_reading.md"
      - Python 与 Scratch: "Python_Projects/python_scratch.md"
  - 开发手册(dev guide):
      - 介绍(introduction): "dev_guide/introduction.md"
      - 架构(Architecture): "dev_guide/Architecture.md"
      - hello world(Adapter Extension): "dev_guide/helloworld.md"
      - json message: "dev_guide/json-message.md"
      - Adapter Node: "dev_guide/Adapter-Node.md"
      - MQTT Adapter Node(正在迁移中): "dev_guide/mqtt-Adapter-Node.md"
      - 同步风格的消息(sync message): "dev_guide/sync-message.md"
      - 编程语言支持(multi language support): "dev_guide/multi-language-support.md"
      - 与其他编程语言集成(system command): "dev_guide/system_command.md"
      - 接入第三方平台: "dev_guide/接入第三方平台.md"
      - 定制与分发: "dev_guide/定制与分发.md"
      - REST API: "dev_guide/REST-API.md"
      - debug: "dev_guide/debug.md"
      - FAQ: "dev_guide/FAQ.md"
      - 安全性(security): "dev_guide/security.md"
      - dev articles: "dev_guide/dev_articles.md"
  - 插件(extensions):
      - 介绍(introduction): "extension_guide/introduction.md"
      - 使用(Usage): "extension_guide/usage.md"
      - extension market: "extension_guide/extension_market.md"
      - micro:bit: "extension_guide/microbit.md"
      - micro:bit radio: "extension_guide/microbit_radio.md"
      - arduino UNO: "extension_guide/arduino_UNO.md"
      - EIM: "extension_guide/eim.md"
      - EIM Monitor: "extension_guide/eim_monitor.md"
      - EIM Trigger: "extension_guide/eim_trigger.md"
      - HCI: "extension_guide/HCI.md"
      - Kano Wand: "extension_guide/Kano_Wand.md"
      - Vector: "extension_guide/vector.md"
      - Cozmo: "extension_guide/cozmo.md"
      - wechat: "extension_guide/wechat.md"
      - webserver: "extension_guide/webserver.md"
      - Python eval kernel: "extension_guide/extension_python_kernel.md"
      - Python exec kernel: "extension_guide/python_exec.md"
      - RoboMaster: "extension_guide/RoboMaster.md"
      - jupyterlab: "extension_guide/jupyterlab.md"
      - Teachable Machine: "extension_guide/teachable_machine.md"
      - Stage: "extension_guide/stage.md"
      - blender: "extension_guide/blender.md"
      - RaspberryPi GPIO: "extension_guide/rpi_gpio.md"
      - Minecraft: "extension_guide/minecraft.md"
      - Sonic Pi : "extension_guide/sonicPi.md"
      - MQTT Adapter: 'extension_guide/MQTT_adapter.md'
      - MQTT Broker : "extension_guide/MQTT_Broker.md"
      - Calypso: "extension_guide/Calypso.md"
      - Box2D: "extension_guide/Box2D.md"
      - physical blocks: "extension_guide/physical_blocks.md"
      - Yanshee: "extension_guide/yanshee.md"
      - json: "extension_guide/json.md"
      - imageData: "extension_guide/imageData.md"
      - home assistant: "extension_guide/ha.md"
      - iot: "extension_guide/iot.md"
      - leap motion: "extension_guide/leapmotion.md"
      - faceapi: "extension_guide/faceapi.md"
      - posenet: "extension_guide/posenet.md"
      - knn: "extension_guide/knn.md"
      - yolo: "extension_guide/yolo.md"
      - Tello: "extension_guide/tello.md"
      - Siri: "extension_guide/siri.md"
      - simple NLU: "extension_guide/simple_NLU.md"
      - kano motion sensor: "extension_guide/motion_sensor.md"
      - UART Adapter: "extension_guide/uart_adapter.md"
      - NetworkZero: "extension_guide/NetworkZero.md"
      - SimplePyboard: "extension_guide/SimplePyboard.md"
      - GameShell: "extension_guide/GameShell.md"
      - Aqara: "extension_guide/Aqara.md"
      - EasyOCR: "extension_guide/EasyOCR.md"
      - tensorflow-yolov4: "extension_guide/tensorflow-yolov4.md"
      - OpenCV(正在迁移中): "extension_guide/opencv.md"
      - Tensorflow(正在迁移中): "extension_guide/tensorflow.md"
      - mpfshell(正在迁移中): "extension_guide/mpfshell.md"
      - Pando Robot(正在迁移中): "extension_guide/Pando.md"
      - Aelos Robot(正在迁移中): "extension_guide/Aelos.md"
      - ROS(正在迁移中): "extension_guide/ROS.md"
  - Scratch插件:
      - 介绍(introduction): "scratch_extensions/introduction.md"
  - 社区版Neverland:
      - 介绍(introduction): "Neverland/index.md"
      - 收工吃饭: "Neverland/finger-snapping.md"
      - 读书与思考: "Neverland/reading-thinking.md"
      - 乐器演奏 (Teachable Machine): "Neverland/musical-instrument-tm.md"
      - 安装Home Assistant: "Neverland/HA.md"
  - CodeLab DynamicTable:
      - 介绍(introduction): "DynamicTable/index.md"
      - hello world: "DynamicTable/hello_world.md"
  - 关于(about):
      - 联系我们(contact us): "about/contact.md"
      - why: "about/why.md"
      - 价值观(value): "about/value.md"
      - 证书(license): "about/License.md"
      # - Changelog: 'changelog.md'
      - 路线图(Roadmap): "about/roadmap.md"

