site_name: scratch3-adapter docs
site_description: the docs
extra:
  search:
    language: 'jp'
pages:
  - Home: 'index.md'
  - 用户手册(user guide):
    - 安装(install): 'user_guide/install.md'
    - 使用(usage): 'user_guide/usage.md'
    - 展示视频(gallery): 'user_guide/gallery.md'
    - FAQ(gallery): 'user_guide/FAQ.md'
  - 开发手册(dev guide):
    - Architecture: 'dev_guide/Architecture.md'
    - hello world: 'dev_guide/helloworld.md'
    - debug: 'dev_guide/debug.md'
    - FAQ: 'dev_guide/FAQ.md'
  - extension guide:
    - 介绍(introduction): 'extension_guide/introduction.md'
    - Cozmo: 'extension_guide/cozmo.md'
  - about:
    - contact us: 'about/contact.md'
    - why: 'about/why.md'
    - value: 'about/value.md'
    - license: 'about/license.md'
    # - Changelog: 'changelog.md'
    - Roadmap: 'about/roadmap.md'

