site_name: CodeLab Adapter
repo_url: https://github.com/Scratch3Lab/codelab-adapter-docs
edit_uri: edit/v2/docs/
site_description: the docs
theme:
  name: material
  language: "zh"
  palette:
    primary: "Light Blue"
    accent: "Light Blue"
  feature:
    tabs: false
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  # - pyembed.markdown

# extra:
#   disqus: 'https-adapter-codelab-club'

# Navigation
nav:
  - 主页(Home): "index.md"
  # - 用户手册(user guide):
  - 用户手册(user guide):
      - 安装(install): "user_guide/install.md"
      # - 下载(download): 'user_guide/develop.md'
      - 使用(usage): "user_guide/usage.md"
      - 展示视频(gallery): "user_guide/gallery.md"
      - 常见问题(FAQ): "user_guide/FAQ.md"
      - 配置文件(settings): "user_guide/settings.md"
      - 历史(changelog): "changelog.md"
  - Scratch Projects:
      - 介绍(introduction): "Scratch_Projects/introduction.md"
      - Scratch PPT: "Scratch_Projects/scratch_ppt.md"
      - 霍格沃兹: "Scratch_Projects/霍格沃兹.md"
      - cube symphony: "Scratch_Projects/cube_symphony.md"
      - 彩虹的旋律: "Scratch_Projects/彩虹的旋律.md"
      - 击掌奏乐: "Scratch_Projects/击掌奏乐.md"
      - 目之所及: "Scratch_Projects/目之所及.md"
      - 芝麻开门: "Scratch_Projects/芝麻开门.md"
      - 纸做的开关: "Scratch_Projects/纸做的开关.md"
      - 自制门禁系统: "Scratch_Projects/自制门禁系统.md"
      - 灰袍巫师: "Scratch_Projects/灰袍巫师.md"
      - 鼻梁上的老花镜: "Scratch_Projects/鼻梁上的老花镜.md"
      - 闭眼请熄灯: "Scratch_Projects/闭眼请熄灯.md"
      - 击灭那盏灯: "Scratch_Projects/击灭那盏灯.md"
      - 手势窗帘: "Scratch_Projects/手势窗帘.md"
  - Python Projects:
      - 介绍(introduction): "Python_Projects/introduction.md"
      - I am reading!: "Python_Projects/I_am_reading.md"
  - 开发手册(dev guide):
      - 介绍(introduction): "dev_guide/introduction.md"
      - 架构(Architecture): "dev_guide/Architecture.md"
      - hello world: "dev_guide/helloworld.md"
      - json message: "dev_guide/json-message.md"
      - Adapter Node: "dev_guide/Adapter-Node.md"
      - MQTT Adapter Node: "dev_guide/mqtt-Adapter-Node.md"
      - 同步风格的消息(sync message): "dev_guide/sync-message.md"
      - 编程语言支持(multi language support): "dev_guide/multi-language-support.md"
      - 与其他编程语言集成(system command): "dev_guide/system_command.md"
      - REST API: "dev_guide/REST-API.md"
      - debug: "dev_guide/debug.md"
      - FAQ: "dev_guide/FAQ.md"
      - 安全性(security): "dev_guide/security.md"
      - dev articles: "dev_guide/dev_articles.md"
  - 插件(extensions):
      - 介绍(introduction): "extension_guide/introduction.md"
      - 使用(Usage): "extension_guide/usage.md"
      - micro:bit: "extension_guide/microbit.md"
      - EIM: "extension_guide/eim.md"
      - Vector: "extension_guide/vector.md"
      - Cozmo: "extension_guide/cozmo.md"
      - wechat: "extension_guide/wechat.md"
      - OpenCV: "extension_guide/opencv.md"
      - Tensorflow: "extension_guide/tensorflow.md"
      - Python kernel extention: "extension_guide/extension_python_kernel.md"
      - mpfshell: "extension_guide/mpfshell.md"
      - blender: "extension_guide/blender.md"
      - Pando Robot: "extension_guide/Pando.md"
      - Tello: "extension_guide/tello.md"
      - Aelos Robot: "extension_guide/Aelos.md"
      - extension market: "extension_guide/extension_market.md"
  - 关于(about):
      - 联系我们(contact us): "about/contact.md"
      - why: "about/why.md"
      - 价值观(value): "about/value.md"
      - 证书(license): "about/License.md"
      # - Changelog: 'changelog.md'
      - 路线图(Roadmap): "about/roadmap.md"

